language: r
sudo: required
apt_packages:
- libmpfr-dev
env:
  global:
    secure: vTgwIeL8/CUCVZbG1p2bXCeYGyo9kirIqtfIYTX3Qmw1STPoiKcpy0ePckC8/qsiA3b0UdPt7Qy5dHEsUceaRY2XNxenYEOTsAuDM2Ye4lhF9FBVsyL9ZY6/zkVuDhFuyCQbv+eX9OmOZaN5NnkvaJadVDwLOR70AX5Kqbg6sydk3SJUcjUPvVfu3V4ARW/BWZsBnpAMkom/0cxiHpXASwURs28NF/PyO9oxuH1gmMWMWt09nA8xAq7YWlx9jTHyeNcjzH/oWYb8Dh39xcoFkR6xaywh0RClZ6sNBbgaKMNJwX4THDymDfwEBgszMDffmNMjExCpAEES1j6ir5OmSKODIZngt+XL30yCLtVzxceB4h/rPKpc0F0GWqJHFz9KqXlV4FVVWH3VmUjepP+iJhBXuO1z0vhbu5+2T8gXLBei534YOiaptB8M3gU94S1zTu5ZcCyoR6jZlLVBFE6QeD0SIL2CsHy2dfy+OeK8NLNmXldTNAlkC+etDUF3RkHpgNlXlCOSJZxxLb0lTY5ST3dZDdVae1bDtu2cUev+Q7QhyEKHEkloXlHxgt+ylDQbmBxPiilAlbh0ON7W76PWnf0nTfVLseTSsRXHT38EnpKnL8XVmmbWmDUedR9RC43+433Cz4zoANMb+FIsS6cbPKY/lzwOQFVm/vPxO2DDmeQ=
