language: r
cache: packages
sudo: required
apt_packages:
- libmpfr-dev
env:
  global:
    secure: F+vTsPhEdCpiT8ruWZq0ovmr7ccX4cBMzEaiUr9otwkkIKMFPSxsFgXiJbltSK00BcK8dTfzJrbj0NTGPL7PaA2DJ+iHGHHyGfnlt4MJMMzlCZdDM+MrLMWVBjSp0Wl3Qcee+avF0IqLwKgiyaxqwuwney7Y8cbXhFpu95PK4hqQTOaJU6VDFl9OkRvgXABDkVuu33gTDZ7/81/fn3Lf1UrU6jk58IrfbRdgFJacdS967TVFdUB6p/UqOURmnc1GNwNrbrBClkk6uihORMdhb/MgmF6MaPOUoGipCHbjvz+rwq0LuA6ejTKWZ+jJ6lihzBdvoI+OorAURvPfx5Wplq+gmywt+Fw2gk4htAOowfodpElTrPVfw8L5MUphZNarkQLW1dp5r4OZZYkWGYu5XEuPgLskofIqUFxTc+17LY7QYB5Y7J4NXjaPdsPrwy0D8yLWRR9ExdgtrdDW+C0NZfDhJpW161i4cRCWEhe5+hBazW++fknxf0k27rkjav+vANDTZo27RQUfVo9LTkJZ5D5v2FYP7vg3IymBzZ8ocZJA6i0kydmD7g64JZoUwVPQMlCsq4LDuxkkpYtoHVSz1RnefvLHkuyff1eHu5LfeFzB4o9sSmk6r6/rdqDZOQ+0GkvdDfIl1R1+YdaOVNn2zioSj97mN9olJQ1KgiuOzeI=
